//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approved
    {
        public int id { get; set; }
        public int Fid { get; set; }
        public int Eid { get; set; }
        public int Rid { get; set; }
        public Nullable<System.DateTime> deliveredtime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Food Food { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
